"""add unique constraint to attendance

Revision ID: f0feb4ca510f
Revises: 49815f6a4fc9
Create Date: 2026-08-17 17:34:49.157463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0feb4ca510f'
down_revision: Union[str, Sequence[str], None] = '49815f6a4fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_attendance_employee_date', 'attendance', ['employee_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_attendance_employee_date', 'attendance', type_='unique')
    # ### end Alembic commands ###
